import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../../models/service.dart';
import '../../models/booking.dart';
import '../../providers/hotel_provider.dart';
import '../../providers/auth_provider.dart';

class ServicePaymentScreen extends StatefulWidget {
  final HotelService service;
  final DateTime bookingDate;
  final String note;

  const ServicePaymentScreen({
    super.key,
    required this.service,
    required this.bookingDate,
    required this.note,
  });

  @override
  State<ServicePaymentScreen> createState() => _ServicePaymentScreenState();
}

class _ServicePaymentScreenState extends State<ServicePaymentScreen> {
  bool isProcessing = false;

  Future<void> _processPayment() async {
    setState(() => isProcessing = true);
    
    // Simulate payment delay
    await Future.delayed(const Duration(seconds: 2));
    
    if (!mounted) return;
    
    final hotelProvider = context.read<HotelProvider>();
    final authProvider = context.read<AuthProvider>();
    
    // Create a standalone booking (roomId is empty)
    final newBooking = Booking(
      id: '', // Will be generated by provider/firestore
      userId: authProvider.user?.uid ?? 'anonymous',
      roomId: '', // Standalone service booking
      checkInDate: widget.bookingDate,
      checkOutDate: widget.bookingDate.add(const Duration(hours: 2)), // Default duration
      totalPrice: widget.service.price,
      status: BookingStatus.confirmed,
      serviceIds: [widget.service.id],
    );
    
    await hotelProvider.addBooking(newBooking);
    
    if (!mounted) return;
    
    setState(() => isProcessing = false);
    
    // Show success dialog
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Center(child: Icon(Icons.check_circle, color: Colors.green, size: 60)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              'Thanh toán thành công!',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
            ),
            const SizedBox(height: 10),
            Text(
              'Đơn hàng cho ${widget.service.name} đã được xác nhận.',
              textAlign: TextAlign.center,
              style: const TextStyle(color: Colors.grey),
            ),
          ],
        ),
        actions: [
          Center(
            child: TextButton(
              onPressed: () {
                Navigator.of(context).popUntil((route) => route.isFirst);
              },
              child: const Text('VỀ TRANG CHỦ', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final currencyFmt = NumberFormat('#,###', 'vi_VN');
    final dateFmt = DateFormat('HH:mm, dd/MM/yyyy');

    return Scaffold(
      appBar: AppBar(
        title: const Text('Thanh toán'),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Tóm tắt đơn hàng',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 20),
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(20),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withAlpha(12),
                    blurRadius: 10,
                    offset: const Offset(0, 5),
                  ),
                ],
              ),
              child: Column(
                children: [
                  _buildSummaryRow('Dịch vụ', widget.service.name),
                  const Divider(height: 30),
                  _buildSummaryRow('Thời gian', dateFmt.format(widget.bookingDate)),
                  const Divider(height: 30),
                  _buildSummaryRow('Ghi chú', widget.note.isEmpty ? 'Không có' : widget.note),
                  const Divider(height: 30),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'TỔNG CỘNG',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                      ),
                      Text(
                        '${currencyFmt.format(widget.service.price)}đ',
                        style: const TextStyle(
                          color: Color(0xFFD4AF37),
                          fontWeight: FontWeight.bold,
                          fontSize: 20,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            const Spacer(),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: isProcessing ? null : _processPayment,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFD4AF37),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 18),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
                  elevation: 0,
                ),
                child: isProcessing
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text(
                        'XÁC NHẬN THANH TOÁN',
                        style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                      ),
              ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildSummaryRow(String label, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(color: Colors.grey)),
        const SizedBox(width: 20),
        Expanded(
          child: Text(
            value,
            textAlign: TextAlign.end,
            style: const TextStyle(fontWeight: FontWeight.bold),
          ),
        ),
      ],
    );
  }
}
