import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../widgets/custom_network_image.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../../models/service.dart';
import '../../models/booking.dart';
import '../../providers/hotel_provider.dart' as hotel_provider;
import '../../providers/auth_provider.dart';
import '../../services/payos_service.dart';

class ServicePaymentScreen extends StatefulWidget {
  final HotelService service;
  final DateTime bookingDate;
  final String note;

  const ServicePaymentScreen({
    super.key,
    required this.service,
    required this.bookingDate,
    required this.note,
  });

  @override
  State<ServicePaymentScreen> createState() => _ServicePaymentScreenState();
}

class _ServicePaymentScreenState extends State<ServicePaymentScreen> {
  final NumberFormat _fmt = NumberFormat('#,###', 'vi_VN');
  
  // PayOS State
  int? _orderCode;
  String? _qrData;
  String? _accountNo;
  String? _accountName;
  String? _bin;
  bool _isLoadingQR = true;
  bool _paymentConfirmed = false;
  Timer? _pollingTimer;

  // Tiền cọc dịch vụ thường tuỳ thuộc vào giá tổng, hoặc ở đây là lấy 100%
  // Tuy nhiên, theo yêu cầu, giao diện hãy làm y chang đặt phòng chờ xử lý
  late int paymentAmount;

  @override
  void initState() {
    super.initState();
    // Giả sử sẽ thu trước toàn bộ tiền dịch vụ (hoặc chỉ cọc, ở đây thu toàn bộ)
    paymentAmount = widget.service.price.toInt(); 
    _initPayosPayment();
  }

  Future<void> _initPayosPayment() async {
    // Generate a unique 8 digit integer for PayOS orderCode
    final codeStr = DateTime.now().millisecondsSinceEpoch.toString();
    final code = int.parse(codeStr.substring(codeStr.length - 8));
    
    // Create the payment link
    final data = await PayOSService.createPaymentLink(
      orderCode: code,
      amount: paymentAmount,
      description: 'DATDICHVU $code',
      cancelUrl: 'https://example.com/cancel',
      returnUrl: 'https://example.com/success',
    );

    if (data != null && mounted) {
      setState(() {
        _orderCode = code;
        _qrData = data['qrCode'];
        _accountNo = data['accountNumber'];
        _accountName = data['accountName'];
        _bin = data['bin'];
        _isLoadingQR = false;
      });
      _startPolling(code);
    } else if (mounted) {
      setState(() => _isLoadingQR = false);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Không thể tạo mã thanh toán PayOS')),
      );
    }
  }

  void _startPolling(int orderCode) {
    _pollingTimer = Timer.periodic(const Duration(seconds: 3), (timer) async {
      final status = await PayOSService.getPaymentStatus(orderCode);
      if (status == 'PAID' && !_paymentConfirmed) {
        timer.cancel();
        if (mounted) {
          setState(() => _paymentConfirmed = true);
          _handlePaymentSuccess();
        }
      }
    });
  }

  Future<void> _handlePaymentSuccess() async {
    try {
      final hotelProvider = context.read<hotel_provider.HotelProvider>();
      final authProvider = context.read<AuthProvider>();
      
      // Create a standalone booking (roomId is empty)
      final newBooking = Booking(
        id: '', // Will be generated by provider/firestore
        userId: authProvider.user?.uid ?? 'anonymous',
        roomId: '', // Standalone service booking
        checkInDate: widget.bookingDate,
        checkOutDate: widget.bookingDate.add(const Duration(hours: 2)), // Default duration
        totalPrice: widget.service.price,
        status: BookingStatus.confirmed, // Cập nhật luôn confirmed khi payos thành công
        serviceIds: [widget.service.id],
      );
      
      await hotelProvider.addBooking(newBooking);
      
      if (mounted) _showConfirmationDialog();
    } catch (e) {
      debugPrint('Auto confirm error: $e');
    }
  }

  @override
  void dispose() {
    _pollingTimer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_paymentConfirmed) {
      return const Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.check_circle, color: Colors.green, size: 80),
              SizedBox(height: 16),
              Text('Thanh toán thành công!', style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
              SizedBox(height: 8),
              Text('Đang chuyển hướng...'),
            ],
          ),
        ),
      );
    }

    final dateFmt = DateFormat('HH:mm, dd/MM/yyyy');

    return Scaffold(
      backgroundColor: const Color(0xFFF5F5F5),
      appBar: AppBar(
        title: const Text('Thanh toán dịch vụ'),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            // Header amount
            Container(
              width: double.infinity,
              color: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 24),
              child: Column(
                children: [
                  const Text('Tổng thanh toán dịch vụ', style: TextStyle(color: Colors.grey, fontSize: 14)),
                  const SizedBox(height: 8),
                  Text(
                    '${_fmt.format(paymentAmount)} ₫',
                    style: const TextStyle(
                      fontSize: 32,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFFD4AF37),
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Dịch vụ: ${widget.service.name}',
                    style: TextStyle(color: Colors.grey[600], fontSize: 14),
                  ),
                  const SizedBox(height: 8),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 40),
                    child: Text(
                      'Thời gian: ${dateFmt.format(widget.bookingDate)}',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.grey[500], fontSize: 12),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),

            // QR Code Card
            Container(
              color: Colors.white,
              margin: const EdgeInsets.symmetric(horizontal: 16),
              padding: const EdgeInsets.all(20),
              child: Column(
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                        decoration: BoxDecoration(
                          color: const Color(0xFF003087),
                          borderRadius: BorderRadius.circular(6),
                        ),
                        child: Text(_bin != null ? _bin! : 'BANK', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                      ),
                      const SizedBox(width: 10),
                      const Text('Mã QR tự động', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                      const Spacer(),
                      CachedNetworkImage(
                        imageUrl: 'https://vietqr.io/img/VIETQR.svg',
                        height: 20,
                        placeholder: (context, url) => const SizedBox(width: 40, height: 20),
                        errorWidget: (context, url, stack) => const SizedBox(),
                      ),
                    ],
                  ),
                  const Divider(height: 24),

                  // QR Code Graphic
                  Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.grey[200]!),
                    ),
                    padding: const EdgeInsets.all(16),
                    child: _isLoadingQR 
                      ? const SizedBox(
                          width: 200, height: 200, 
                          child: Center(child: CircularProgressIndicator())
                        )
                      : _qrData != null 
                        ? CustomPaint(
                            size: const Size.square(200),
                            painter: QrPainter(
                              data: _qrData!,
                              version: QrVersions.auto,
                              errorCorrectionLevel: QrErrorCorrectLevel.L,
                            ),
                          )
                        : const SizedBox(
                            width: 200, height: 200, 
                            child: Center(child: Icon(Icons.error_outline, size: 50, color: Colors.red))
                          ),
                  ),
                  const SizedBox(height: 16),
                  
                  if (_isLoadingQR) 
                    const Text('Đang tạo mã QR PayOS...', style: TextStyle(color: Colors.grey))
                  else if (_accountName != null) ...[
                    Text(_accountName!, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                    const SizedBox(height: 4),
                    Text(_accountNo!, style: TextStyle(color: Colors.grey[600], fontSize: 16)),
                  ],
                ],
              ),
            ),
            const SizedBox(height: 12),

            // Transfer info
            if (!_isLoadingQR && _orderCode != null)
              Container(
                color: Colors.white,
                margin: const EdgeInsets.symmetric(horizontal: 16),
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Thông tin chuyển khoản', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                    const SizedBox(height: 16),
                    _infoRow('Số tài khoản', _accountNo ?? '', copyable: true),
                    const Divider(height: 20),
                    _infoRow('Nội dung CK', 'DATDICHVU $_orderCode', copyable: true, highlight: true),
                    const Divider(height: 20),
                    _infoRow('Số tiền', '${_fmt.format(paymentAmount)} ₫', copyable: true),
                    if (widget.note.isNotEmpty) ...[
                      const Divider(height: 20),
                      _infoRow('Ghi chú của bạn', widget.note),
                    ],
                  ],
                ),
              ),
            const SizedBox(height: 12),

            // Warning
            Container(
              margin: const EdgeInsets.symmetric(horizontal: 16),
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.green[50],
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.green[200]!),
              ),
              child: Row(
                children: [
                  Icon(Icons.autorenew, color: Colors.green[700], size: 24),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      'Hệ thống đang tự động kiểm tra giao dịch liên tục. Bạn KHÔNG CẦN bấm nút xác nhận nào cả.',
                      style: TextStyle(color: Colors.green[800], fontSize: 13, height: 1.4, fontWeight: FontWeight.bold),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 100),
          ],
        ),
      ),
    );
  }

  Widget _infoRow(String label, String value, {bool copyable = false, bool highlight = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Expanded(
          flex: 1,
          child: Text(label, style: TextStyle(color: Colors.grey[600]))
        ),
        Expanded(
          flex: 2,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              Flexible(
                child: Text(
                  value,
                  textAlign: TextAlign.end,
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    color: highlight ? const Color(0xFFD4AF37) : Colors.black,
                  ),
                  maxLines: 2,
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              if (copyable) ...[
                const SizedBox(width: 8),
                GestureDetector(
                  onTap: () {
                    Clipboard.setData(ClipboardData(text: value.replaceAll(' ₫', '').replaceAll('.', '').trim()));
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('Đã sao chép!'), duration: Duration(seconds: 1)),
                    );
                  },
                  child: Icon(Icons.copy, size: 16, color: Colors.grey[400]),
                ),
              ],
            ],
          ),
        ),
      ],
    );
  }

  void _showConfirmationDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        contentPadding: const EdgeInsets.all(24),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.green[50],
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.check_circle, color: Colors.green, size: 64),
            ),
            const SizedBox(height: 20),
            const Text(
              'Thanh toán thành công!',
              style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              'Dịch vụ ${widget.service.name} đã được xác nhận.',
              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            const Text(
              'Hệ thống PayOS đã tự động ghi nhận giao dịch của bạn. Bạn hãy đến đúng giờ nhé.',
              style: TextStyle(color: Colors.grey, fontSize: 14, height: 1.5),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: () {
                  Navigator.of(ctx).pop();
                  Navigator.of(context).popUntil((route) => route.isFirst);
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFD4AF37),
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  elevation: 0,
                ),
                child: const Text('Về trang chủ', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
